### ISSUE TITLE
Some Problems of Preprocessing

### ISSUE THREAD

**Issue by ccmoe** [VisionLearningGroup/caption-guided-saliency#12]
Hello，
When I was ready for / TestVideo and test_videodatainfo.json, I received some errors at runtime.I tried to set the shell parameter value of the Popen function to True and run it, but I couldn't get the *.jpg file.I hope to get your help.The error appears as follows：

` File "/***/preprocessing.py", line 121, in extract_features_msr_vtt
    extract_frames(video, dst)
  File "/***/caption-guided-saliency-master/preprocessing.py", line 101, in extract_frames
    subprocess.call(video_to_frames_command, stdout=ffmpeg_log, stderr=ffmpeg_log)
  File "/home/***/anaconda2/envs/python27/lib/python2.7/subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/home/***/anaconda2/envs/python27/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/***/anaconda2/envs/python27/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

**Comment by ramanishka** [comment]
Hi,

Does the file exist? 
Could you debug it to see which file is missing? E.g. the content of `video_to_frames_command`

**Comment by ccmoe** [comment]
@ramanishka ,This is the first time I use ffmpeg to extract frames. I don't know if I need to install some packages to use ffmpeg. After the function extract_frames() is executed successfully, (the above problem is not reported as wrong) the video frame cannot be obtained. I'm confused

**Comment by ramanishka** [comment]
@ccmoe In your previous message, you've mentioned "No such file or directory" error. Now you're saying that extract_frames() was executed successfully. Which one is correct?
