### ISSUE TITLE
The "test_videodatainfo.json" is not available from MSR anymore

### ISSUE THREAD

**Issue by Peratham** [VisionLearningGroup/caption-guided-saliency#3]
Hi, 

The "test_videodatainfo.json" is not available from MSR-VTT official website anymore. So, right now we cannot execute "run_s2vt.py --test" anymore. It generates an error at line 67.

Can you please provide the "test_videodatainfo.json"?

Thanks,
Peratham

**Comment by Peratham** [comment]
They still provide "test_annotation.zip" but there is no "test_videodatainfo.json". It has "test_videodatainfo_nosen.json" instead which means there is no sentence annotation release anymore...

**Comment by Peratham** [comment]
OK. I found the link http://ms-multimedia-challenge.com/static/resource/test_videodatainfo.json. They just removed the old test data when they updated their webpage for the 2017 competition.

**Comment by ramanishka** [comment]
Hi!
Thanks for pointing to this. Indeed, they rearranged the data for 2017 challenge but old versions are still available (maybe temporarily) by direct links. I added them to [readme](https://github.com/VisionLearningGroup/caption-guided-saliency/blob/master/README.md).

Right now they provide only json with an index and links to 10k files on YouTube. Some of original files might be deleted from YouTube.

**Comment by Peratham** [comment]
:)

**Comment by Victoria2333** [comment]
@ramanishka Hi, the download of "train_val_annovation.zip" always failed, do you know where i can find them?
@Peratham Hi,I see you find test_annotation.zip, could you offer me the link?

Thanks,
Victoria
