### ISSUE TITLE
dataset link 

### ISSUE THREAD

**Issue by Victoria2333** [VisionLearningGroup/caption-guided-saliency#5]
@ramanishka 
Hi, the download of "train_val_annovation.zip" always failed.
Could you offer me the link of train_val_annotation.zip and test_annotation.zip?I couln't find them.

Thanks,
Victoria

**Comment by ramanishka** [comment]
Resolved

**Comment by ghost** [comment]
I cannot download the MSR-VTT and Flickr30k
please give the link

**Comment by ramanishka** [comment]
To access the datasets, please, follow the instructions: 

for Flickr30k
http://shannon.cs.illinois.edu/DenotationGraph/

for MSR-VTT
http://ms-multimedia-challenge.com/2017/dataset

**Comment by ghost** [comment]
however I do not konw how to download the  MSR-VTT:train_val_videos.zip, train_val_annotation.zip, test_videos.zip, test_videodatainfo.json from http://ms-multimedia-challenge.com/2017/dataset
could you help me ?
