### ISSUE TITLE
Can you give the link to download MSR-VTT dataset? I can only download json file from official website

### ISSUE THREAD

**Issue by xiadingZ** [VisionLearningGroup/caption-guided-saliency#6]

**Comment by ramanishka** [comment]
For MSR-VTT v1 10k original video? You can download/preprocess them according to the json index organizers provided. Otherwise, try this: https://www.mediafire.com/folder/h14iarbs62e7p/shared

**Comment by xiadingZ** [comment]
Thanks a lot!

**Comment by hugddygff** [comment]
where to download the csv files???

**Comment by xiadingZ** [comment]
sorry, I make a mistake, it's json file.

**Comment by akonstantinou** [comment]
> For MSR-VTT v1 10k original video? You can download/preprocess them according to the json index organizers provided. Otherwise, try this: https://www.mediafire.com/folder/h14iarbs62e7p/shared

I tried to use the mediafire file but it is not exactly correct. There are many videos missing audio (around 1200 of them). I checked many of them on youtube and they actually have audio. Is there any other source to download the correct dataset?

**Comment by simonJJJ** [comment]
Hi, is there any way to download the MSR-VTT dataset, the link seems to be expired.

**Comment by 5RJ** [comment]
https://www.kaggle.com/datasets/vishnutheepb/msrvtt?resource=download

**Comment by learn2phoenix** [comment]
@5RJ  Doesn't this contain only the videos? Where do we find the annotations?
